[package]
name = "stackable-secret-operator"
authors = ["Stackable GmbH <info@stackable.de>"]
description = "Stackable Operator for managing credentials"
license = "OSL-3.0"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/stackabletech/secret-operator"

[dependencies]
anyhow = "1.0.52"
async-trait = "0.1.52"
futures = "0.3.18"
openssl = "0.10.38"
pin-project = "1.0.8"
prost = "0.9.0"
prost-types = "0.9.0"
serde = "1.0.130"
serde_json = "1.0.74"
serde_yaml = "0.8.23"
snafu = "0.7.0"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git", tag = "0.6.0" }
structopt = "0.3.25"
time = "0.3.5"
tokio = { version = "1.14.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = "0.6.1"
tonic-reflection = "0.3.0"
tracing = "0.1.29"

[build-dependencies]
tonic-build = "0.6.0"

[patch.crates-io]
# Workaround for https://github.com/hyperium/tonic/issues/243
h2 = { git = "https://github.com/teozkr/h2.git", branch = "feature/grpc-uds" }

kube = { git = "https://github.com/teozkr/kube-rs.git", branch = "feature/crd-complex-enum" }
kube-core = { git = "https://github.com/teozkr/kube-rs.git", branch = "feature/crd-complex-enum" }
kube-derive = { git = "https://github.com/teozkr/kube-rs.git", branch = "feature/crd-complex-enum" }
# kube = { path = "../../kube-rs/kube" }
# kube-core = { path = "../../kube-rs/kube-core" }
# kube-derive = { path = "../../kube-rs/kube-derive" }

[features]
