[package]
name = "stackable-secret-operator"
license = "OSL-3.0"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
futures = "0.3.18"
pin-project = "1.0.8"
prost = "0.9.0"
prost-types = "0.9.0"
serde = "1.0.130"
stackable-operator = { git = "https://github.com/stackabletech/operator-rs.git" }
structopt = "0.3.25"
thiserror = "1.0.30"
tokio = { version = "1.14.0", features = ["full"] }
tokio-stream = { version = "0.1.8", features = ["net"] }
tonic = "0.6.1"
tonic-reflection = "0.3.0"
tracing = "0.1.29"

[build-dependencies]
tonic-build = "0.6.0"

[patch.crates-io]
# Workaround for https://github.com/hyperium/tonic/issues/243
h2 = { git = "https://github.com/teozkr/h2.git", branch = "feature/grpc-uds" }

[features]
