---
name: pre-commit

on:
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always
  RUST_TOOLCHAIN_VERSION: "nightly-2025-05-26"

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Install host dependencies
        uses: awalsh128/cache-apt-pkgs-action@5902b33ae29014e6ca012c5d8025d4346556bd40 # v1.4.3
        with:
          packages: krb5-user libkrb5-dev libclang-dev liblzma-dev libssl-dev pkg-config apt-transport-https
          version: ubuntu-latest
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: stackabletech/actions/run-pre-commit@4bfd3b65f22af597fe784599c077dc34bf5894a7 # v0.8.0
        with:
          rust: ${{ env.RUST_TOOLCHAIN_VERSION }}
          # rust-src is required for trybuild stderr output comparison to work
          # for our cases.
          # See: https://github.com/dtolnay/trybuild/issues/236#issuecomment-1620950759
          rust-components: rustfmt,clippy,rust-src
